### ISSUE TITLE
bug: string is not well-formed UTF-16 (emoji?)

### ISSUE THREAD

**Issue by hafidzaini** [thisissandipp/typethis#11]
## 🐞 Bug

════════ Exception caught by painting library ══════════════════════════════════
The following ArgumentError was thrown while building a TextSpan:
Invalid argument(s): string is not well-formed UTF-16

is this because of emoji in string?

**Comment by justsandip** [comment]
Hi @hafidzaini,

Thanks for opening this issue. Would you please share the code for the `TypeThis` widget you used and resulted into this error? It'll easy for me to reproduce the bug and troubleshoot.

**Comment by hafidzaini** [comment]
hello @thecodexhub , i use string from AI function return, maybe its because contain Emoji and or Markdown.
i regex removing emoji and markdown, error gone.

raw print API end point response:
I/flutter (21271): Hey there, trader! It's Monday, September 16th, 2024, and it's 4:23 PM. Let's make today a profitable one!  May all your trades be green and your gains be plentiful. 💰📈  Good luck out there!  🍀

**Comment by justsandip** [comment]
Okay, I understand. Thanks for clarifying and providing the sample text.

I'll look into this issue today and let you know once I find the root cause of this error.

**Comment by hafidzaini** [comment]
thank you very much

**Comment by hafidzaini** [comment]
is it possible to pass another style instead of string ? as Markdown maybe?
so we can just pass the AI API endpoint result and make it mimic typing like ChatGPT app, Copilot app, etc?

**Comment by justsandip** [comment]
The `ArgumentError` occurs due to the presence of Unicode characters (emojis). The `typethis` package operates by maintaining a `currentStep` that increments over time with a timer. This `currentStep` is used to determine the number of characters to display using the `substring` method.

Here's the issue, if you run the code snippet below, it returns a length of 2 instead of the expected 1.

```dart
var s = "🎉";
print(s.length); // 2
```

This happens because certain Unicode characters, like emojis, are represented by more than one code unit in Dart's String. As a result, when the program tries to render `s.substring(0, 1)`, it encounters an `ArgumentError` since it doesn't correctly account for the emoji's multi-unit representation.

---

This can be solved by using the [Characters API](https://pub.dev/packages/characters), let me think through this. This is currently **work in progress**.

Anyways, this is a great catch. And thanks again for opening this issue. 🚀

**Comment by hafidzaini** [comment]
ah .. thats why..
i was trying manually with some emoji but not all of them resulted in an error.
thanks for this explanation

**Comment by justsandip** [comment]
Hey @hafidzaini, I've published the v1.0.2 version of the package with this issue fixed. This should work fine now.

---

> is it possible to pass another style instead of string ? as Markdown maybe? so we can just pass the AI API endpoint result and make it mimic typing like ChatGPT app, Copilot app, etc?

About this, it's a good idea. I'll create a separate issue to track.

**Comment by hafidzaini** [comment]
Thank you very much
